[build]
  publish = "."
  functions = "functions"

[dev]
  publish = "."
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 